### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grindtildeath** [odoo/mail-client-extensions#30]
Hello

AFAICS there is no license defined on this repository.

Could you guys please define one to avoid any missunderstanding on how are we allowed to reuse the code?

**Comment by grindtildeath** [comment]
ping @std-odoo @Florimond @nounoubensebia @tde-banana-odoo

**Comment by std-odoo** [comment]
@odony Hi :) 

Here is the PR to add the licences files (copy / paste from the odoo/odoo repo) https://github.com/odoo/mail-client-extensions/pull/31

can you r+ it ?

**Comment by tde-banana-odoo** [comment]
Fixed with https://github.com/odoo/mail-client-extensions/commit/a7774cd056417704144486c3d15b1760e862adb6
